version: "2.1"
services:
  plex:
    image: artificiallyintelligent/plex-rclone
    container_name: plex
    network_mode: bridge
    devices:
      - "/dev/fuse:/dev/fuse"
    cap_add:
      - SYS_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
      - "RCLONE_CONFIG=/config/rclone/rclone.conf"
      - "RCLONE_MOUNT_CONTAINER_PATH=/mnt/rclone"
      - "RCLONE_MOUNT_REMOTE_PATH=CRYPT:"
      - "RCLONE_MOUNT_OPTIONS= --read-only --acd-templink-threshold 0 --buffer-size 1G --timeout 5s --contimeout 5s --log-level INFO --stats 60s --dir-cache-time 24h "
      - RCLONE_GUI=TRUE
      - "RCLONE_DRIVE_SCOPE=drive.readonly" # for connection to google drive remote https://rclone.org/drive/ 
      - "RCLONE_DRIVE_TEAM_DRIVE=<your team drive id - can be found in rclone.conf>"
      - 'RCLONE_CONFIG_REMOTE_CLIENT_ID=<your googledrive client id - optional - can be found in rclone.conf as "client_id">'
      - 'RCLONE_CONFIG_REMOTE_CLIENT_SECRET=<your secret associated with your googledrive client id - optional - can be found in rclone.conf as "secret">'
      - 'RCLONE_CONFIG_REMOTE_TOKEN=<your auth token json created with "rclone config" - can be found in rclone.conf as "token">'
      - "RCLONE_CRYPT_PASSWORD=<your encryption password or pass phrase>" # for decrypting remote contents https://rclone.org/crypt/
      - "RCLONE_CRYPT_PASSWORD2=<your encryption password or pass phrase for salt>"
      - "RCLONE_CRYPT_DIRECTORY_NAME_ENCRYPTION=true"
      - "RCLONE_CRYPT_FILENAME_ENCRYPTION=standard"
      - PLEXDRIVE=TRUE
    volumes:
      - plex_temp:/transcode
      - plex_config:/config
    ports:
      - "32400:32400"
      - "32410-32414:32410-32414"
      - "32469:32469"
      - "8384:8384"
      - "3005:3005"
      - "1900:1900"
      - "13668-13670:13668-13670"
    restart: unless-stopped
volumes:
  plex_temp:
  plex_config:
