#!/usr/bin/with-contenv bash

# UMASK_SET=${UMASK_SET:-022}
# umask "$UMASK_SET"

echo ----------------------------------------------------------
echo ----------------------------------------------------------
echo "Starting Rclone."
echo ----------------------------------------------------------
echo
exec \
        /bin/bash -c \
        '/usr/bin/mount-rclone'

# delay between retries if failing to mount
sleep 5