#!/usr/bin/with-contenv bash

# UMASK_SET=${UMASK_SET:-022}
# umask "$UMASK_SET"

echo "Starting Plexdrive Rclone Crypt."
exec \
        /bin/bash -c \
        '/usr/bin/mount-plexdrive --mount-crypt'
